ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>': 'Andreas Isaak <andy.jared@googlemail.com>'
  'Stefan Heimes <stefan_heimes@hotmail.com>': 'Stefan heimes <stefan_heimes@hotmail.com>'
  'Christopher Boelter <christopher@boelter.eu>':
    - 'cboelter <christopher@boelter.eu>'
    - 'Christopher Boelter <christopher@boelter.eu>'
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'xantippe <info@e-spin.de>'
    - 'zonky2 <info@e-spin.de>'
    - 'zonky <gitlab@e-spin.de>'

copy-left:
  'Ingolf Steinhardt <info@e-spin.de>':
    - src/EventListener/RgXpOptionsListener.php
  'Stefan Heimes <stefan_heimes@hotmail.com>':
    - src/EventListener/RgXpOptionsListener.php
  'Sven Baumann <baumann.sv@gmail.com>':
    - src/EventListener/RgXpOptionsListener.php
